import type { Skill } from "./types";

export const BUSINESS_SKILLS: Skill[] = [
  {
    id: "business-plan",
    name: "Business Plan Builder",
    category: "business",
    description: "Turn an idea into a structured, realistic business plan.",
    purpose: "Produce a plan that pressure-tests the idea instead of just describing it optimistically.",
    whenToUse: "Shaping a new venture, product line, or pitch.",
    inputs: ["The idea, target customer, and any constraints (budget, timeline, market)"],
    outputs: ["A plan: problem · solution · market · model · go-to-market · costs · risks · milestones"],
    steps: [
      "Clarify the core idea, the customer, and the problem it solves. If the target customer is unclear, ask one question.",
      "Work through: problem & evidence it's real, solution, market size signal, revenue model, go-to-market, cost structure, and key risks.",
      "Be honest about the weakest assumption — name it explicitly.",
      "Define the first milestones that would validate or kill the idea cheaply.",
      "Critique the plan for optimism bias and hand-waving, then revise once.",
    ],
    behaviorGuidelines: ["Pressure-test, don't cheerlead", "Name the riskiest assumption", "Prefer cheap validation over big bets"],
    toolsAllowed: ["WebSearch", "WebFetch", "Read"],
    toolsDisallowed: ["Bash"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Build a business plan for a meal-prep service for busy parents", "Turn this app idea into a plan"],
    successCriteria: ["Every section is concrete and idea-specific", "The weakest assumption is named", "Milestones validate cheaply"],
    failureModes: ["Generic boilerplate", "Ignoring the risky assumption", "No path to validation"],
    followUpBehavior: "Offer to build the go-to-market plan or the first-90-days milestones in detail.",
  },
  {
    id: "pricing-strategy",
    name: "Pricing Strategy",
    category: "business",
    description: "Design a pricing model grounded in value, costs, and the market.",
    purpose: "Recommend a pricing structure that captures value without scaring off the target customer.",
    whenToUse: "Setting or revising prices for a product or service.",
    inputs: ["What you sell, who buys it, your costs, and competitor pricing if known"],
    outputs: ["A recommended model + tiers/price points with rationale and what to test"],
    steps: [
      "Establish the value to the customer, your unit cost/floor, and competitor price points (research if needed).",
      "Pick a model that fits the buyer (one-time, subscription, usage, tiered, value-based) and justify it.",
      "Propose concrete price points/tiers and what each tier includes; anchor against the value and the market.",
      "Identify the riskiest pricing assumption and a cheap way to test it (e.g. a willingness-to-pay check).",
      "Critique for leaving money on the table vs pricing out the buyer, then revise once.",
    ],
    behaviorGuidelines: ["Anchor on value, not just cost-plus", "Justify the model, don't default to subscription", "Recommend a test for the risky assumption"],
    toolsAllowed: ["WebSearch", "WebFetch", "Read"],
    toolsDisallowed: ["Bash"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["How should I price my SaaS for small agencies?", "Design pricing tiers for this product"],
    successCriteria: ["Model fits the buyer and value", "Concrete price points with rationale", "A clear thing to test"],
    failureModes: ["Pure cost-plus with no value lens", "Arbitrary numbers", "Defaulting to subscription unexamined"],
    followUpBehavior: "Offer to draft the pricing page copy or the test plan.",
  },
  {
    id: "proposal-sow",
    name: "Proposal / SOW",
    category: "business",
    description: "Draft a scoped proposal / statement of work with an explicit out-of-scope list.",
    purpose: "Win the work and prevent scope creep with concrete deliverables and boundaries.",
    whenToUse: "Quoting a project for a client or stakeholder.",
    inputs: ["The engagement, client outcome, constraints, and any rates"],
    outputs: ["Overview · Objectives · Scope · Out of scope · Timeline · Pricing structure · Assumptions · Acceptance"],
    steps: [
      "Identify the client's desired outcome, constraints, and what success means to them. Ask one question only if timeline/budget genuinely blocks scoping.",
      "Define scope as concrete deliverables and an explicit out-of-scope list — the best defense against scope creep.",
      "Lay out phases/milestones, a timeline, and a pricing structure (fixed / T&M / retainer) with rationale; use clearly-marked placeholders if no rates were given.",
      "Add assumptions, client responsibilities, and sign-off acceptance criteria.",
      "Critique that no deliverable can be misread as larger than intended, then revise once.",
    ],
    behaviorGuidelines: ["Out-of-scope list is mandatory", "Never fabricate dollar figures", "Make deliverables unambiguous"],
    toolsAllowed: ["Read", "Write"],
    toolsDisallowed: ["Bash"],
    safetyLevel: "writes-files",
    confirmationRequired: false,
    examplePrompts: ["Write a SOW for a 6-week website rebuild", "Draft a proposal for ongoing managed IT support"],
    successCriteria: ["Scope is airtight with an out-of-scope list", "Pricing structure is clear", "Acceptance criteria are defined"],
    failureModes: ["No out-of-scope boundaries", "Invented pricing", "Vague deliverables"],
    followUpBehavior: "Offer to tighten any section and list the 2-3 items to confirm before sending.",
  },
  {
    id: "sop-builder",
    name: "SOP / Process Builder",
    category: "business",
    description: "Document a repeatable process as a clear standard operating procedure.",
    purpose: "Turn tribal knowledge into a step-by-step process anyone can follow consistently.",
    whenToUse: "A recurring task should be standardized, delegated, or made auditable.",
    inputs: ["The process to document and who will follow it"],
    outputs: ["An SOP: purpose · when it applies · steps · roles · checks · what to do when it fails"],
    steps: [
      "Clarify the process's goal, who performs it, and how often. If the trigger is unclear, ask one question.",
      "Write the steps in exact order — concrete actions a new person could follow without guessing, including the expected result of each.",
      "Add roles/ownership, decision points, quality checks, and an escalation/exception path for when something goes wrong.",
      "Critique: could someone new execute this correctly the first time? Remove assumed knowledge, then revise once.",
    ],
    behaviorGuidelines: ["Write for someone who has never done it", "Concrete actions, not aspirations", "Include the failure/escalation path"],
    toolsAllowed: ["Read", "Write"],
    toolsDisallowed: ["Bash"],
    safetyLevel: "writes-files",
    confirmationRequired: false,
    examplePrompts: ["Write an SOP for onboarding a new client", "Document our monthly invoicing process"],
    successCriteria: ["A newcomer can follow it without asking", "Roles and checks are explicit", "Failure path included"],
    failureModes: ["Assuming prior knowledge", "Vague steps", "No exception handling"],
    followUpBehavior: "Offer a one-page checklist version for day-to-day use.",
  },
  {
    id: "customer-persona",
    name: "Customer Persona Builder",
    category: "business",
    description: "Build a grounded customer persona that guides product and messaging.",
    purpose: "Define who you're really building/selling for, with their goals, pains, and objections.",
    whenToUse: "Sharpening product decisions, messaging, or targeting.",
    inputs: ["Your product and any real customer signals (interviews, reviews, data)"],
    outputs: ["A persona: who they are · goals · pains · buying triggers · objections · where to reach them"],
    steps: [
      "Anchor on real signal where it exists (reviews, interviews, support tickets) rather than inventing a demographic.",
      "Define the persona's job-to-be-done, goals, and the specific pains your product addresses.",
      "Capture buying triggers, the objections they'll raise, and the channels where they actually are.",
      "Critique: is this specific enough to make a product/messaging decision, or is it a generic stereotype? Revise once.",
    ],
    behaviorGuidelines: ["Ground in real signal, flag what's assumed", "Job-to-be-done over demographics", "Specific enough to act on"],
    toolsAllowed: ["WebSearch", "WebFetch", "Read"],
    toolsDisallowed: ["Bash"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Build a persona for the buyer of a $99/mo agency tool", "Who is the ideal customer for this app?"],
    successCriteria: ["Specific enough to drive a decision", "Pains and objections are concrete", "Assumptions are flagged"],
    failureModes: ["Generic stereotype", "Demographics with no job-to-be-done", "Presenting guesses as facts"],
    followUpBehavior: "Offer to turn the persona into messaging or a landing-page angle.",
  },
];
