import type { Skill } from "./types";

export const CODING_SKILLS: Skill[] = [
  {
    id: "codebase-audit",
    name: "Codebase Audit",
    category: "coding",
    description: "Map an unfamiliar project and report architecture, risks, and quick wins.",
    purpose: "Give a fast, evidence-based understanding of a codebase before you commit to changes.",
    whenToUse: "Starting on a new repo, inheriting a project, or scoping a large change.",
    inputs: ["An open project folder (or a path to one)", "Optionally, a focus area"],
    outputs: ["A report: Stack · Architecture · Risks · Quick wins, with file:line citations"],
    steps: [
      "Identify the stack: read package.json / Cargo.toml / pyproject / go.mod and the lockfile; name frameworks, language versions, and scripts.",
      "Map structure: glob the top 2-3 directory levels (skip node_modules/target/dist); identify entry points, the build, and how it runs.",
      "Read the 5-10 most important files (entry points, core modules, config) — not everything.",
      "Summarize what the project does and its data/control flow.",
      "Flag risks with file:line evidence: security, fragile abstractions, dead code, missing tests, doc drift.",
      "Critique the draft against the success criteria, then present 3-5 ordered, high-impact, low-risk improvements.",
    ],
    behaviorGuidelines: [
      "Work from what the code actually says, never assumptions.",
      "Cite real files and lines so claims are checkable.",
      "Prioritize signal over completeness — don't read the whole tree.",
    ],
    toolsAllowed: ["Glob", "Grep", "Read", "Bash"],
    toolsDisallowed: ["Write", "Edit"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Audit this codebase", "What is this repo and where are the risks?"],
    successCriteria: [
      "Stack and entry points are correctly identified",
      "Every risk cites a real file:line",
      "Recommendations are specific and ordered by impact",
    ],
    failureModes: ["Inventing structure without reading", "Vague risks with no citation", "Reading the entire tree and running out of context"],
    followUpBehavior: "Offer to fix the top quick win or go deeper on any flagged risk.",
  },
  {
    id: "build-feature",
    name: "Build New Feature",
    category: "coding",
    description: "Implement a feature end-to-end with a plan, code, and verification.",
    purpose: "Ship a non-trivial feature that matches the codebase's conventions and is actually verified.",
    whenToUse: "Adding new functionality beyond a one-line change.",
    inputs: ["A description of the feature and its acceptance criteria"],
    outputs: ["Working code", "A list of files changed", "Evidence it builds/tests pass"],
    steps: [
      "Restate the goal and acceptance criteria in 1-2 lines.",
      "Explore the relevant existing code so the new work matches conventions.",
      "Lay out a short plan (files to add/change, in order); surface decisions that need input.",
      "Implement in small, logical steps matching the surrounding style; add types/validation where the codebase already uses them.",
      "Build/typecheck and run the relevant tests; fix failures before reporting done.",
      "Report what changed, how you verified it, and any follow-ups.",
    ],
    behaviorGuidelines: [
      "Match existing patterns rather than introducing new ones.",
      "Never claim it works without running the build/tests.",
      "Ask one question only if a decision genuinely blocks progress.",
    ],
    toolsAllowed: ["Read", "Glob", "Grep", "Edit", "Write", "Bash"],
    toolsDisallowed: [],
    safetyLevel: "runs-commands",
    confirmationRequired: false,
    examplePrompts: ["Add a dark-mode toggle that persists to localStorage", "Build a /health endpoint that checks the DB"],
    successCriteria: ["Feature meets the stated acceptance criteria", "Build/tests pass", "Style matches the codebase"],
    failureModes: ["Skipping verification", "Reinventing patterns", "Sprawling diff that does more than asked"],
    followUpBehavior: "Summarize the diff and offer to add tests or wire it into the UI/routes.",
  },
  {
    id: "debug-error",
    name: "Debug Error",
    category: "coding",
    description: "Diagnose a failure from evidence and propose the minimal fix.",
    purpose: "Find the real root cause of a bug and fix that, not the symptom.",
    whenToUse: "Something is throwing, failing, or behaving wrong.",
    inputs: ["The error/stack trace or a description of the wrong behavior"],
    outputs: ["Root cause", "The minimal fix", "How it was confirmed"],
    steps: [
      "Reproduce or locate the failure — read the actual error and the code at those lines.",
      "Form a root-cause hypothesis and confirm it by reading code or running a check.",
      "Propose the minimal fix and explain why it addresses the cause, not the symptom.",
      "Apply it (if edits are allowed), then verify by re-running the failing path.",
      "Report root cause · fix · confirmation; if unconfirmed, say so with the evidence.",
    ],
    behaviorGuidelines: ["Distinguish root cause from symptom explicitly", "Prefer the smallest change that fixes the cause", "Don't guess when you can check"],
    toolsAllowed: ["Read", "Grep", "Glob", "Bash", "Edit"],
    toolsDisallowed: [],
    safetyLevel: "runs-commands",
    confirmationRequired: false,
    examplePrompts: ["This test fails with a null pointer — fix it", "Why does the build break on CI but not locally?"],
    successCriteria: ["The root cause is identified and supported", "The fix resolves the failing path", "The change is minimal"],
    failureModes: ["Patching the symptom", "Large speculative refactors", "Claiming a fix without re-running"],
    followUpBehavior: "Offer a regression test that would have caught this.",
  },
  {
    id: "generate-tests",
    name: "Generate Tests",
    category: "coding",
    description: "Write meaningful tests for a unit, including edge and failure cases.",
    purpose: "Add tests that actually exercise behavior, using the project's existing framework.",
    whenToUse: "Coverage is missing, or you changed risky code.",
    inputs: ["The function/module/file to test"],
    outputs: ["Passing tests in the project's framework", "A note on what's covered and any gaps"],
    steps: [
      "Find an existing test and match its framework, structure, and conventions.",
      "Cover the happy path, the important edge cases, and at least one failure case.",
      "Prefer behavior-level assertions over implementation details.",
      "Run the suite and confirm the tests pass and can actually fail.",
      "Report what's covered and any gaps you deliberately left.",
    ],
    behaviorGuidelines: ["A test that can't fail is worthless — verify it bites", "Don't restate the implementation in assertions", "Use the existing test framework, don't introduce a new one"],
    toolsAllowed: ["Read", "Glob", "Grep", "Write", "Edit", "Bash"],
    toolsDisallowed: [],
    safetyLevel: "runs-commands",
    confirmationRequired: false,
    examplePrompts: ["Write tests for the date parser", "Add edge-case tests for this validation function"],
    successCriteria: ["Tests pass and exercise real behavior", "Edge + failure cases included", "Matches project conventions"],
    failureModes: ["Tautological tests", "Wrong framework", "Only the happy path"],
    followUpBehavior: "Report coverage and offer to test adjacent untested code.",
  },
  {
    id: "review-pull-request",
    name: "Review Pull Request",
    category: "coding",
    description: "Review a diff for correctness, security, and clarity — not just style nits.",
    purpose: "Catch real bugs and risks in a change before it merges.",
    whenToUse: "Before merging a branch or reviewing a teammate's diff.",
    inputs: ["A branch, PR, or a description of what changed"],
    outputs: ["Prioritized findings with file:line, severity, and a concrete fix each"],
    steps: [
      "Read the diff (git diff / the changed files) and enough surrounding code to judge it.",
      "Check correctness first: logic bugs, edge cases, error handling, race conditions.",
      "Then security (injection, authz, secrets), then performance, then clarity.",
      "For each finding give file:line, severity, why it matters, and a concrete fix.",
      "Critique your own list — drop non-issues, then present findings ordered by severity.",
    ],
    behaviorGuidelines: ["Lead with correctness and security, not formatting", "Don't pad the list with trivia", "Be specific enough that the author can act without asking"],
    toolsAllowed: ["Bash", "Read", "Grep", "Glob"],
    toolsDisallowed: ["Write", "Edit"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Review the changes on this branch", "Review my diff before I merge"],
    successCriteria: ["Real bugs/risks surfaced with evidence", "Each finding is actionable", "Severity-ordered, no noise"],
    failureModes: ["Only style nits", "Vague 'consider refactoring'", "Missing an obvious correctness bug"],
    followUpBehavior: "Offer to apply the high-severity fixes.",
  },
  {
    id: "optimize-performance",
    name: "Optimize Performance",
    category: "coding",
    description: "Find and fix the actual bottleneck, measured — not guessed.",
    purpose: "Make code measurably faster by targeting the real hot path.",
    whenToUse: "Something is slow and you need it faster.",
    inputs: ["What's slow and, if possible, how it's measured"],
    outputs: ["The identified bottleneck", "A targeted fix", "Before/after evidence"],
    steps: [
      "Establish how slowness is measured (a timing, a profile, a benchmark). If none exists, add a quick measurement first.",
      "Locate the actual hot path with evidence — don't optimize on intuition.",
      "Propose the highest-leverage change (algorithm, query, caching, N+1, allocation).",
      "Apply it, then re-measure to prove it helped.",
      "Report the bottleneck, the change, and the before/after numbers.",
    ],
    behaviorGuidelines: ["Measure before and after — no unverified speedups", "Target the dominant cost, not micro-optimizations", "Don't sacrifice correctness for speed"],
    toolsAllowed: ["Read", "Grep", "Glob", "Bash", "Edit"],
    toolsDisallowed: [],
    safetyLevel: "runs-commands",
    confirmationRequired: false,
    examplePrompts: ["This endpoint takes 4s — make it faster", "The page load is slow, find the bottleneck"],
    successCriteria: ["Bottleneck identified with evidence", "Measured improvement", "Correctness preserved"],
    failureModes: ["Optimizing the wrong thing", "No measurement", "Premature micro-optimization"],
    followUpBehavior: "Report the numbers and flag the next bottleneck if one remains.",
  },
  {
    id: "refactor-module",
    name: "Refactor Module",
    category: "coding",
    description: "Improve structure without changing behavior, verified by tests.",
    purpose: "Make code cleaner and more maintainable while proving behavior is unchanged.",
    whenToUse: "Code works but is messy, duplicated, or hard to extend.",
    inputs: ["The module/file to refactor"],
    outputs: ["Refactored code", "Confirmation that behavior is unchanged (tests/build green)"],
    steps: [
      "Read the module and its call sites; note the public surface that must stay stable.",
      "Identify the specific smells (duplication, long functions, weak abstractions, tangled deps).",
      "Make focused, reversible changes one concern at a time, keeping names/patterns consistent.",
      "After each meaningful step run the build/tests; if there are no tests for this code, say so and add a couple of characterization tests first.",
      "Report what improved and confirm behavior is unchanged.",
    ],
    behaviorGuidelines: ["Behavior must not change", "One concern per step", "Verify with tests/build, don't assume"],
    toolsAllowed: ["Read", "Glob", "Grep", "Edit", "Bash"],
    toolsDisallowed: [],
    safetyLevel: "runs-commands",
    confirmationRequired: false,
    examplePrompts: ["Refactor this 300-line function", "Clean up this module, it's a mess"],
    successCriteria: ["Behavior unchanged (tests/build green)", "Real structural improvement", "Consistent with the codebase"],
    failureModes: ["Changing behavior", "Big-bang rewrite", "No verification"],
    followUpBehavior: "Confirm tests green and offer to refactor an adjacent rough spot.",
  },
  {
    id: "create-react-component",
    name: "Create React Component",
    category: "coding",
    description: "Scaffold a React component matching the project's conventions and states.",
    purpose: "Build a typed, accessible component that fits the existing codebase.",
    whenToUse: "Adding a new frontend component.",
    inputs: ["What the component does and where it's used"],
    outputs: ["The component file(s), wired in, building clean"],
    steps: [
      "Inspect a couple of existing components to match framework, styling approach, file layout, and prop patterns.",
      "Build it: typed props, sensible defaults, accessible markup, the project's styling system (don't introduce a new one).",
      "Handle empty/loading/error states if it fetches or can be empty.",
      "Wire it where asked (or show where), then typecheck/build and report the files added.",
    ],
    behaviorGuidelines: ["Match existing conventions, don't invent new ones", "Typed props + accessible markup", "Handle non-happy states"],
    toolsAllowed: ["Read", "Glob", "Grep", "Write", "Edit", "Bash"],
    toolsDisallowed: [],
    safetyLevel: "runs-commands",
    confirmationRequired: false,
    examplePrompts: ["Create a Toast component", "Build a data table component with sorting"],
    successCriteria: ["Matches project conventions", "Typed + accessible", "Builds clean"],
    failureModes: ["New styling system", "Untyped props", "Ignoring loading/empty states"],
    followUpBehavior: "Offer to add tests or a usage example.",
  },
  {
    id: "create-api-route",
    name: "Create API Route",
    category: "coding",
    description: "Add a backend route with validation, auth, and structured errors.",
    purpose: "Add an endpoint that matches the project's patterns and is safe by default.",
    whenToUse: "Adding a server endpoint.",
    inputs: ["What the endpoint should do and its inputs/outputs"],
    outputs: ["The route, building clean, with validation and error handling"],
    steps: [
      "Read a sibling route to match the project's routing, validation, and error-handling patterns.",
      "Implement with input validation, auth/permission checks consistent with the codebase, and structured success + error responses.",
      "Avoid injection and unbounded inputs; keep secrets out of code.",
      "Typecheck/build and report the route signature, validation, and error shape.",
    ],
    behaviorGuidelines: ["Match the existing route patterns", "Validate inputs and check auth", "Never hardcode secrets"],
    toolsAllowed: ["Read", "Glob", "Grep", "Write", "Edit", "Bash"],
    toolsDisallowed: [],
    safetyLevel: "runs-commands",
    confirmationRequired: false,
    examplePrompts: ["Add a POST /api/orders route", "Create an endpoint to export user data as CSV"],
    successCriteria: ["Matches existing patterns", "Validates input + checks auth", "Structured errors, builds clean"],
    failureModes: ["No input validation", "Inconsistent error shape", "Missing auth checks"],
    followUpBehavior: "Offer to add a test or wire it into the client.",
  },
  {
    id: "explain-codebase",
    name: "Explain Codebase",
    category: "coding",
    description: "Explain how a project or a specific flow works, grounded in the code.",
    purpose: "Help someone understand a codebase or a particular path through it, from the actual source.",
    whenToUse: "Onboarding to a repo, or trying to understand how a feature works.",
    inputs: ["The project (open it) and what you want explained (the whole thing or a specific flow)"],
    outputs: ["A clear explanation with the key files and the data/control flow, cited"],
    steps: [
      "Scope the question: the whole architecture, or one specific flow (e.g. 'how does login work')?",
      "Trace it through the real code — entry point → the files/functions involved → the data flow — reading, not guessing.",
      "Explain it at the right altitude: the big picture first, then the key files, then the important details.",
      "Cite the files so the user can follow along, and flag anything surprising or fragile you noticed.",
    ],
    behaviorGuidelines: ["Trace the actual code, never guess", "Big picture before details", "Cite files so it's followable"],
    toolsAllowed: ["Read", "Glob", "Grep"],
    toolsDisallowed: ["Write", "Edit"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Explain how this app is structured", "Walk me through how authentication works in this repo"],
    successCriteria: ["Accurate to the code", "Right altitude for the question", "Key files cited"],
    failureModes: ["Guessing instead of reading", "Too much detail or too vague", "No file references"],
    followUpBehavior: "Offer to go deeper on any file or trace another flow.",
  },
];
