import type { Skill } from "./types";

export const CREATIVE_SKILLS: Skill[] = [
  {
    id: "brainstorm-ideas",
    name: "Brainstorm Ideas",
    category: "creative",
    description: "Generate a wide range of genuinely different ideas, then narrow to the best.",
    purpose: "Produce real divergent options (not five variations of one idea) and a shortlist.",
    whenToUse: "You're stuck or want more/better options than you'd get alone.",
    inputs: ["What you're brainstorming, the goal, and any constraints"],
    outputs: ["A diverse idea list, then a shortlist of the strongest with why"],
    steps: [
      "Clarify the goal and the constraints that ideas must respect.",
      "Generate broadly: cover safe, ambitious, and unconventional angles — push past the obvious first 3.",
      "Group the ideas and cut near-duplicates so the list is genuinely diverse.",
      "Shortlist the strongest 3-5 against the goal and say why each made it.",
      "Critique that the list isn't all variations of one theme, then add 1-2 from a missing angle.",
    ],
    behaviorGuidelines: ["Diverge before converging", "Genuinely different angles, not variations", "Then narrow with reasons"],
    toolsAllowed: ["WebSearch"],
    toolsDisallowed: ["Bash"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Brainstorm ways to promote my new app", "Give me ideas for a team offsite"],
    successCriteria: ["Ideas are genuinely diverse", "Constraints respected", "A reasoned shortlist"],
    failureModes: ["Five versions of one idea", "Ignoring constraints", "No narrowing"],
    followUpBehavior: "Offer to develop the top idea or push a specific angle further.",
  },
  {
    id: "name-generator",
    name: "Name Generator",
    category: "creative",
    description: "Generate brandable names for a product, project, or company, with rationale.",
    purpose: "Produce memorable, available-feeling names across distinct naming styles — not a thesaurus dump.",
    whenToUse: "Naming a product, company, feature, or project.",
    inputs: ["What you're naming, what it does, the vibe, and any must-haves/avoids"],
    outputs: ["Named options grouped by style, each with a one-line rationale + availability caveats"],
    steps: [
      "Clarify what it is, the intended feel (serious/playful/technical), and any constraints (length, .com, avoid words).",
      "Generate across distinct styles: descriptive, evocative/metaphor, invented/coined, and compound — a few each.",
      "For each, give a one-line rationale; flag obviously taken or trademark-risky ones and recommend checking domains/trademarks.",
      "Shortlist the strongest few and say why; critique for ones that are hard to spell/say, then revise once.",
    ],
    behaviorGuidelines: ["Span multiple naming styles", "Note that availability must be checked — don't promise it", "Flag hard-to-spell/say names"],
    toolsAllowed: ["WebSearch"],
    toolsDisallowed: ["Bash"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Name a budgeting app for couples", "Generate company names for a homelab automation tool"],
    successCriteria: ["Variety across naming styles", "Each has a rationale", "Availability caveat included"],
    failureModes: ["One style only", "Promising a name is 'available'", "Unpronounceable coinages"],
    followUpBehavior: "Offer to check domain availability or develop a tagline for the favorite.",
  },
  {
    id: "content-calendar",
    name: "Content Calendar Builder",
    category: "creative",
    description: "Plan a content calendar with themes, formats, and a realistic cadence.",
    purpose: "Turn 'we should post more' into a concrete, sustainable content plan.",
    whenToUse: "Planning marketing/social/blog content over weeks or months.",
    inputs: ["Audience, channels, goals, cadence you can sustain, and key dates"],
    outputs: ["A dated calendar: themes, post ideas, formats, and channels — at a realistic cadence"],
    steps: [
      "Confirm the audience, channels, goal (awareness/leads/etc.), and the cadence the user can actually sustain.",
      "Define a few content pillars/themes that ladder up to the goal.",
      "Schedule concrete post ideas across the period, balanced across formats and mapped to channels and key dates.",
      "Keep the cadence realistic — better a sustainable plan than an ambitious one that dies in week two.",
      "Critique for repetitiveness and over-ambition, then revise once.",
    ],
    behaviorGuidelines: ["Cadence must be sustainable", "Themes ladder to the goal", "Concrete post ideas, not just 'post about X'"],
    toolsAllowed: ["WebSearch", "Write"],
    toolsDisallowed: ["Bash"],
    safetyLevel: "writes-files",
    confirmationRequired: false,
    examplePrompts: ["Build a 1-month content calendar for my SaaS on LinkedIn", "Plan content themes for our product launch"],
    successCriteria: ["Realistic, sustainable cadence", "Concrete post ideas mapped to channels", "Themes serve the goal"],
    failureModes: ["Unsustainable volume", "Vague 'post about the product'", "No theme/structure"],
    followUpBehavior: "Offer to draft the first week's posts.",
  },
  {
    id: "ad-copy",
    name: "Ad Copy Generator",
    category: "creative",
    description: "Write ad copy variations grounded in a real value prop and audience.",
    purpose: "Produce ad copy that's specific and testable, with distinct angles to A/B.",
    whenToUse: "Writing ads for a product/service across channels.",
    inputs: ["The product, the audience, the one core benefit, the channel, and any constraints (length, CTA)"],
    outputs: ["Several ad variations across distinct angles, each with headline + body + CTA"],
    steps: [
      "Pin the single most compelling benefit for this audience and the channel's format/limits. If the core benefit is unclear, ask one question.",
      "Write variations across distinct angles (benefit-led, problem-led, social-proof, curiosity) — not reworded twins.",
      "Keep claims grounded in what's true; make the CTA specific.",
      "Critique each for specificity and a clear hook, cut the weakest, then revise once.",
    ],
    behaviorGuidelines: ["Ground claims in reality — no invented stats", "Distinct angles for real A/B testing", "Specific CTA, not 'learn more' by default"],
    toolsAllowed: ["WebSearch"],
    toolsDisallowed: ["Bash"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Write Google Ads copy for my bookkeeping service", "Ad variations for this app launch"],
    successCriteria: ["Distinct, testable angles", "Grounded claims", "Specific hooks and CTAs"],
    failureModes: ["Reworded duplicates", "Invented claims/stats", "Generic 'learn more'"],
    followUpBehavior: "Offer channel-specific lengths or a landing-page headline to match.",
  },
];
