import type { Skill } from "./types";

export const DATA_SKILLS: Skill[] = [
  {
    id: "csv-analyzer",
    name: "CSV / Data Analyzer",
    category: "data",
    description: "Explore a dataset and surface the findings that actually matter.",
    purpose: "Go from a raw CSV/table to real insights, not just descriptive stats.",
    whenToUse: "You have a data file and a question (or want to know what's interesting).",
    inputs: ["A path to the data file (or pasted data)", "Optionally, the question you care about"],
    outputs: ["Key findings · notable patterns/outliers · data caveats · answer to your question"],
    steps: [
      "Read the file and understand its shape: columns, types, row count, and the grain (what one row represents).",
      "Check data quality first — missing values, obvious errors, duplicates — and note caveats that affect conclusions.",
      "Answer the user's question if they gave one; otherwise surface the 3-5 most decision-relevant findings.",
      "Quantify findings (numbers, not 'a lot') and flag outliers worth a human's attention.",
      "Critique for spurious patterns and overreach, then revise once.",
    ],
    behaviorGuidelines: ["Verify data quality before drawing conclusions", "Quantify everything", "Don't claim causation from correlation"],
    toolsAllowed: ["Read", "Bash"],
    toolsDisallowed: ["Write", "Edit"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["What's interesting in this sales.csv?", "Analyze this data and tell me why revenue dropped"],
    successCriteria: ["Findings are quantified and decision-relevant", "Data caveats are stated", "The user's question is answered if asked"],
    failureModes: ["Reporting stats with no insight", "Ignoring data-quality issues", "Implying causation"],
    followUpBehavior: "Offer a chart recommendation or a deeper cut on the most interesting finding.",
  },
  {
    id: "formula-builder",
    name: "Spreadsheet Formula Builder",
    category: "data",
    description: "Write and explain the exact spreadsheet formula you need.",
    purpose: "Produce a correct, copy-pasteable formula and explain how it works.",
    whenToUse: "You're stuck building a spreadsheet formula.",
    inputs: ["What you want to compute, the columns/cells involved, and Excel vs Google Sheets"],
    outputs: ["The formula, an explanation, and edge-case notes"],
    steps: [
      "Confirm the goal, the relevant cell ranges, and the target tool (Excel / Google Sheets) — they differ. Ask one question only if the layout is ambiguous.",
      "Write the exact formula using the right functions; prefer robust, readable forms over clever one-liners.",
      "Explain what each part does so the user can adapt it.",
      "Call out edge cases (blanks, errors, division-by-zero, text vs number) and how the formula handles them.",
      "Critique by mentally running it on a tricky row, then revise once.",
    ],
    behaviorGuidelines: ["Match the exact tool's syntax", "Handle blanks/errors gracefully", "Explain so the user can modify it"],
    toolsAllowed: [],
    toolsDisallowed: ["Bash"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["A formula to sum column C where column A = 'paid'", "VLOOKUP keeps erroring, what's the right formula?"],
    successCriteria: ["Formula is correct for the stated tool", "Edge cases handled or noted", "Clear enough to adapt"],
    failureModes: ["Wrong tool's syntax", "Breaks on blanks/errors", "Cryptic with no explanation"],
    followUpBehavior: "Offer a variant (array/spill, or error-wrapped) if relevant.",
  },
  {
    id: "data-quality-check",
    name: "Data Quality Checker",
    category: "data",
    description: "Audit a dataset for the problems that would corrupt any analysis.",
    purpose: "Find missing, malformed, duplicate, and inconsistent data before anyone trusts it.",
    whenToUse: "Before analyzing or importing a dataset you didn't create.",
    inputs: ["A path to the dataset"],
    outputs: ["A quality report: issues found, severity, affected rows/columns, and suggested fixes"],
    steps: [
      "Read the data and establish the expected schema (types, required fields, valid ranges).",
      "Check for: missing values, type mismatches, duplicates, out-of-range/impossible values, and inconsistent formats/categories.",
      "Quantify each issue (how many rows, which columns) and rate its severity for downstream use.",
      "Suggest a concrete fix for each (drop, impute, normalize, dedupe) without applying it unless asked.",
      "Critique for issues you might have missed in skewed columns, then revise once.",
    ],
    behaviorGuidelines: ["Quantify every issue", "Rate severity for actual use", "Suggest fixes but don't mutate the data unasked"],
    toolsAllowed: ["Read", "Bash"],
    toolsDisallowed: ["Write", "Edit"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Check this CSV for data quality issues", "Is this dataset clean enough to analyze?"],
    successCriteria: ["Real issues found and quantified", "Severity rated for use", "Fixes suggested, data untouched"],
    failureModes: ["Vague 'some missing values'", "Missing impossible values", "Silently altering the data"],
    followUpBehavior: "Offer to apply the suggested cleanups (with confirmation) and re-check.",
  },
  {
    id: "budget-analyzer",
    name: "Budget Analyzer",
    category: "data",
    description: "Make sense of a budget or expense data and find what to act on.",
    purpose: "Turn budget/spend numbers into a clear picture and concrete savings/risks.",
    whenToUse: "Reviewing a budget, expenses, or spend data.",
    inputs: ["The budget/expense data and the period it covers"],
    outputs: ["Where the money goes · trends · anomalies · concrete savings or risks"],
    steps: [
      "Read the data and confirm the period, categories, and whether figures are actuals vs planned.",
      "Summarize where the money actually goes (top categories, % of total) — concrete numbers.",
      "Identify trends (rising/falling) and anomalies (spikes, unexpected line items) worth attention.",
      "Surface the highest-leverage savings opportunities or financial risks, with the number attached.",
      "Critique for misread categories/periods, then revise once.",
    ],
    behaviorGuidelines: ["Always attach the number", "Separate actuals from plan", "Flag anomalies, don't smooth them"],
    toolsAllowed: ["Read", "Bash"],
    toolsDisallowed: ["Write", "Edit"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Analyze this expense report and find savings", "Where is most of our budget going?"],
    successCriteria: ["Clear picture of where money goes", "Anomalies and trends surfaced with numbers", "Actionable savings/risks"],
    failureModes: ["Restating totals with no insight", "Confusing planned with actual", "Generic 'cut costs' advice"],
    followUpBehavior: "Offer a category deep-dive or a simple month-over-month view.",
  },
];
