import type { Skill } from "./types";

export const DESIGN_SKILLS: Skill[] = [
  {
    id: "ui-critic",
    name: "UI Critic",
    category: "design",
    description: "Critique an interface for hierarchy, clarity, and usability with concrete fixes.",
    purpose: "Improve a UI by finding the real usability and visual-hierarchy problems, not opinions.",
    whenToUse: "You have a screen/component and want it sharper before shipping.",
    inputs: ["The UI (code, a screenshot description, or the component) and what the user is trying to do on it"],
    outputs: ["Prioritized issues: hierarchy, clarity, consistency, affordances — each with a concrete fix"],
    steps: [
      "Establish the primary user task on this screen and the intended action.",
      "Evaluate visual hierarchy (is the primary action obvious?), clarity (labels, states), consistency (spacing, type, color), and affordances (do things look interactive?).",
      "For each issue, give the specific fix (increase contrast on the CTA, group these fields, add an empty state) tied to the task.",
      "Prioritize by how much each blocks or slows the user, and critique for personal-taste calls vs real usability. Revise once.",
    ],
    behaviorGuidelines: ["Tie every critique to the user's task", "Concrete fixes, not 'make it cleaner'", "Separate usability facts from taste"],
    toolsAllowed: ["Read", "Glob", "Grep"],
    toolsDisallowed: ["Bash"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Critique this settings screen", "Review the UX of this React component"],
    successCriteria: ["Real hierarchy/usability issues found", "Each has a concrete fix", "Prioritized by user impact"],
    failureModes: ["Taste-based nitpicks", "'Make it pop' vagueness", "Missing the unclear primary action"],
    followUpBehavior: "Offer to implement the top fixes in the code.",
  },
  {
    id: "landing-page-critic",
    name: "Landing Page Critic",
    category: "design",
    description: "Review a landing page for clarity, persuasion, and conversion.",
    purpose: "Make a landing page communicate value fast and drive the intended action.",
    whenToUse: "You have a landing page and want more of the right visitors to convert.",
    inputs: ["The page (copy + structure or the code) and the single conversion goal"],
    outputs: ["Findings on the hero, value prop, proof, CTA, and friction — with concrete rewrites/fixes"],
    steps: [
      "Confirm the single conversion goal and the target visitor.",
      "Check the hero first: in 5 seconds, is it clear what this is, who it's for, and why it's better?",
      "Then value prop clarity, social proof, CTA prominence/wording, and friction (length, jargon, asks).",
      "Give concrete rewrites for the weakest elements (especially the headline and CTA), prioritized by conversion impact.",
      "Critique for guessing without the goal in mind, then revise once.",
    ],
    behaviorGuidelines: ["The hero's 5-second test comes first", "Rewrite weak copy, don't just flag it", "Prioritize by conversion impact"],
    toolsAllowed: ["Read", "WebFetch", "Glob", "Grep"],
    toolsDisallowed: ["Bash"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Critique my landing page for conversions", "Why isn't this page converting?"],
    successCriteria: ["Hero clarity assessed", "Concrete copy/CTA rewrites given", "Prioritized by conversion impact"],
    failureModes: ["Generic 'add testimonials'", "Flagging without rewriting", "Ignoring the actual goal"],
    followUpBehavior: "Offer A/B variants for the headline and CTA.",
  },
  {
    id: "accessibility-review",
    name: "Accessibility Review",
    category: "design",
    description: "Find accessibility barriers and give specific, standards-based fixes.",
    purpose: "Make an interface usable for people with disabilities, against real WCAG criteria.",
    whenToUse: "Before shipping UI, or auditing an existing interface for a11y.",
    inputs: ["The UI code or component"],
    outputs: ["Issues by type (contrast, keyboard, semantics, labels, focus) with severity and fixes"],
    steps: [
      "Review the markup/code for semantic structure, alt text, form labels, and ARIA usage.",
      "Check keyboard operability (focus order, visible focus, no traps) and color contrast against WCAG AA.",
      "Check for screen-reader pitfalls: missing labels, non-semantic clickable divs, unannounced state changes.",
      "Report each issue with the WCAG criterion, severity, and the specific code fix.",
      "Critique for issues only visible in interaction (focus, live regions), then revise once.",
    ],
    behaviorGuidelines: ["Cite the specific barrier, not 'improve a11y'", "Give the exact code fix", "Cover keyboard + screen reader, not just contrast"],
    toolsAllowed: ["Read", "Glob", "Grep"],
    toolsDisallowed: ["Bash"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Review this component for accessibility", "Is this form accessible?"],
    successCriteria: ["Real barriers found across types", "Each has a concrete fix", "Severity rated"],
    failureModes: ["Only checking contrast", "Vague advice", "Missing keyboard/focus issues"],
    followUpBehavior: "Offer to apply the high-severity fixes.",
  },
  {
    id: "conversion-review",
    name: "Conversion Rate Review",
    category: "design",
    description: "Find where users drop off in a flow and how to reduce the friction.",
    purpose: "Improve completion of a key flow (signup, checkout, onboarding) by removing friction.",
    whenToUse: "A funnel or flow is leaking users and you want to fix it.",
    inputs: ["The flow (steps/screens or code) and where you think users drop", "Any data you have"],
    outputs: ["Friction points per step · likely drop-off causes · prioritized changes to test"],
    steps: [
      "Map the flow step by step and the action required at each.",
      "At each step, identify friction: unnecessary fields, unclear value, surprise costs, decision overload, trust gaps.",
      "Hypothesize where the biggest drop-off is and why; if data exists, ground it in the data.",
      "Recommend specific changes and what to A/B test, ordered by expected lift.",
      "Critique for guessing the wrong step, then revise once.",
    ],
    behaviorGuidelines: ["Go step by step — friction hides in specific steps", "Hypotheses tied to the step", "Recommend testable changes, ordered by expected lift"],
    toolsAllowed: ["Read", "WebFetch", "Glob", "Grep"],
    toolsDisallowed: ["Bash"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Why do users drop off in our signup flow?", "Review this checkout for conversion friction"],
    successCriteria: ["Per-step friction identified", "Drop-off hypothesis is specific", "Testable, ranked changes"],
    failureModes: ["Generic 'simplify the flow'", "No step-level analysis", "Untestable suggestions"],
    followUpBehavior: "Offer to spec the top experiment or implement the easiest fix.",
  },
];
