import type { Skill } from "./types";

export const DOCUMENT_SKILLS: Skill[] = [
  {
    id: "presentation-outline",
    name: "Presentation Outline Builder",
    category: "documents",
    description: "Build a slide-by-slide outline with a clear narrative arc.",
    purpose: "Structure a talk/deck so it tells one story and lands its point, before any design.",
    whenToUse: "You need to build a presentation and want the structure right first.",
    inputs: ["The topic, audience, the single takeaway, and the time/slide budget"],
    outputs: ["A slide-by-slide outline: each slide's one point + supporting content + the narrative arc"],
    steps: [
      "Pin the audience, the single takeaway they should leave with, and the time/slide budget. If the takeaway is unclear, ask one question.",
      "Design the arc: hook → context → core argument (3 beats) → implication → call to action.",
      "Give each slide ONE point and the supporting content; cut anything that doesn't serve the takeaway.",
      "Critique: does every slide advance the one story, and is it the right length? Revise once.",
    ],
    behaviorGuidelines: ["One idea per slide", "Everything serves the single takeaway", "Structure before decoration"],
    toolsAllowed: ["Read"],
    toolsDisallowed: ["Bash"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Outline a 10-slide pitch deck for investors", "Build a deck outline to explain our roadmap to the team"],
    successCriteria: ["Clear narrative arc", "One point per slide", "Fits the slide/time budget"],
    failureModes: ["Slides with no single point", "No arc, just topics", "Over budget"],
    followUpBehavior: "Offer to write speaker notes or the actual slide copy.",
  },
  {
    id: "slide-deck-critic",
    name: "Slide Deck Critic",
    category: "documents",
    description: "Critique a deck for narrative, clarity, and slide-level effectiveness.",
    purpose: "Make an existing deck sharper and more persuasive.",
    whenToUse: "You have a draft deck and want it reviewed before presenting.",
    inputs: ["The deck content (text/outline, or a description per slide)", "The audience and goal"],
    outputs: ["Deck-level and slide-level feedback with concrete fixes, prioritized"],
    steps: [
      "Understand the audience and the deck's goal.",
      "Assess the deck level first: is there one clear story, the right order, and a strong open/close?",
      "Then go slide by slide: is the point clear, is there too much text, does it earn its place?",
      "Give concrete fixes (merge these two, cut this slide, lead with the chart) prioritized by impact.",
      "Critique your feedback for nitpicking, keep what changes the outcome, revise once.",
    ],
    behaviorGuidelines: ["Story-level issues before slide nits", "Concrete edits, not 'make it pop'", "Prioritize by impact on the audience"],
    toolsAllowed: ["Read"],
    toolsDisallowed: ["Bash"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Critique this pitch deck", "Review my deck before the board meeting"],
    successCriteria: ["Narrative issues caught", "Slide feedback is concrete", "Prioritized, not a laundry list"],
    failureModes: ["Only cosmetic notes", "Vague 'add more detail'", "Missing a broken narrative"],
    followUpBehavior: "Offer to rewrite the weakest slides or the opening.",
  },
  {
    id: "one-page-brief",
    name: "One-Page Brief",
    category: "documents",
    description: "Compress a topic into a single, scannable one-pager.",
    purpose: "Give stakeholders everything they need on one page — no more, no less.",
    whenToUse: "Someone needs the whole picture fast, in one document.",
    inputs: ["The topic/source material and who the brief is for"],
    outputs: ["A one-page brief: context · key points · recommendation/ask · next steps"],
    steps: [
      "Identify the reader and the decision or understanding the brief needs to produce.",
      "Lead with the situation and the ask/recommendation; follow with only the supporting points that matter.",
      "Keep it to one page — ruthlessly cut anything the reader doesn't need to act.",
      "Critique: could the reader act from this page alone, and does it actually fit on one page? Revise once.",
    ],
    behaviorGuidelines: ["Recommendation/ask up high", "Strictly one page of essentials", "Scannable structure, not prose blocks"],
    toolsAllowed: ["Read", "Write"],
    toolsDisallowed: ["Bash"],
    safetyLevel: "writes-files",
    confirmationRequired: false,
    examplePrompts: ["Turn this into a one-page brief for leadership", "One-pager on why we should adopt this tool"],
    successCriteria: ["Fits one page", "Reader can act from it alone", "Ask is prominent"],
    failureModes: ["Three pages of 'one-pager'", "Burying the ask", "Dense prose with no scannability"],
    followUpBehavior: "Offer a slide or email version of the same brief.",
  },
  {
    id: "report-writer",
    name: "Report Writer",
    category: "documents",
    description: "Write a structured report grounded in real inputs, with a clear conclusion.",
    purpose: "Produce a report that informs a decision, not a data dump.",
    whenToUse: "You need a formal writeup of findings, status, or analysis.",
    inputs: ["The material/findings to report on, the audience, and the report's purpose"],
    outputs: ["A structured report: summary · findings · analysis · recommendations · appendix"],
    steps: [
      "Clarify the report's purpose and audience, and lead with an executive summary that states the conclusion.",
      "Present findings grounded in the actual inputs (read them); separate fact from interpretation.",
      "Analyze what the findings mean and give recommendations tied to the evidence.",
      "Critique: is it faithful to the inputs, does the summary match the body, is it skimmable? Revise once, then write it out.",
    ],
    behaviorGuidelines: ["Conclusion-first summary", "Separate evidence from interpretation", "Every recommendation traces to a finding"],
    toolsAllowed: ["Read", "Write", "Bash"],
    toolsDisallowed: [],
    safetyLevel: "writes-files",
    confirmationRequired: false,
    examplePrompts: ["Write a report on this quarter's incident data", "Turn these findings into a formal report"],
    successCriteria: ["Summary states the conclusion", "Findings grounded in inputs", "Recommendations trace to evidence"],
    failureModes: ["Data dump with no conclusion", "Summary that doesn't match the body", "Unsupported recommendations"],
    followUpBehavior: "Offer an executive-summary-only version for wider distribution.",
  },
];
