import type { Skill } from "./types";

export const IT_SKILLS: Skill[] = [
  {
    id: "homelab-audit",
    name: "Homelab Audit",
    category: "it",
    description: "Inventory a homelab/server setup and flag config, security, and reliability gaps.",
    purpose: "Understand what's running and surface the risks before they bite.",
    whenToUse: "Reviewing a self-hosted setup, or before adding more to it.",
    inputs: ["Access to the host(s) or a description of what's running"],
    outputs: ["Inventory · security gaps · reliability risks (backups, single points of failure) · prioritized fixes"],
    steps: [
      "Inventory what's running: services, containers, ports, and how they're exposed (read configs, ps, listening ports — don't change anything).",
      "Check security posture: exposed ports, default creds risk, missing auth, outdated images, secrets in plaintext.",
      "Check reliability: backups (exist? tested?), single points of failure, restart policies, disk headroom.",
      "Prioritize fixes by risk (likelihood × blast radius) and flag the top 3.",
      "Critique for the boring-but-deadly gaps (no tested backups, exposed admin UI), then revise once.",
    ],
    behaviorGuidelines: ["Read-only — never change config during an audit", "Prioritize by real blast radius", "Untested backups = no backups"],
    toolsAllowed: ["Bash", "Read", "Grep"],
    toolsDisallowed: ["Write", "Edit"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Audit my homelab setup", "What are the security and reliability gaps on this server?"],
    successCriteria: ["Accurate inventory", "Security + reliability gaps found", "Prioritized fixes"],
    failureModes: ["Changing config mid-audit", "Missing the exposed admin panel", "Ignoring backups"],
    followUpBehavior: "Offer to fix the top risk (with confirmation) or build a hardening checklist.",
  },
  {
    id: "network-troubleshooting",
    name: "Network Troubleshooting",
    category: "it",
    description: "Diagnose a connectivity or networking problem methodically, layer by layer.",
    purpose: "Find where a network path actually breaks instead of guessing.",
    whenToUse: "Something can't connect, resolve, or route and you need to find out why.",
    inputs: ["The symptom (what can't reach what) and the topology if known"],
    outputs: ["The point of failure, the cause, and the fix — with the evidence at each layer"],
    steps: [
      "Restate the exact symptom: what source can't reach what destination, and how it fails (timeout, refused, DNS, slow).",
      "Work the layers in order: link/IP (can you ping?), DNS (does it resolve?), routing/firewall (is the port reachable?), then the service itself.",
      "At each layer run the check and record the result — narrow to the first layer that fails.",
      "Identify the cause at the failing layer and the specific fix.",
      "Critique: did you confirm the fix resolves the original symptom? If not, verify before claiming done.",
    ],
    behaviorGuidelines: ["Go layer by layer — don't skip to a guess", "Record the result at each step", "Confirm the fix against the original symptom"],
    toolsAllowed: ["Bash", "Read"],
    toolsDisallowed: ["Write", "Edit"],
    safetyLevel: "runs-commands",
    confirmationRequired: false,
    examplePrompts: ["My container can't reach the database, help me debug", "DNS isn't resolving for this service"],
    successCriteria: ["Failing layer pinpointed with evidence", "Cause and fix identified", "Fix verified against the symptom"],
    failureModes: ["Guessing without layer checks", "Fixing a layer that wasn't broken", "Not verifying"],
    followUpBehavior: "Offer to apply the fix (with confirmation) and re-test the path.",
  },
  {
    id: "docker-compose-review",
    name: "Docker Compose Review",
    category: "it",
    description: "Review a docker-compose file for correctness, security, and reliability.",
    purpose: "Catch the compose mistakes that cause outages, data loss, or exposure.",
    whenToUse: "Before deploying or after writing/changing a compose stack.",
    inputs: ["The docker-compose.yml (and related .env / Dockerfile if relevant)"],
    outputs: ["Findings by area: data persistence, security, networking, reliability — with concrete fixes"],
    steps: [
      "Read the compose file and understand the stack and how services relate.",
      "Check data: are stateful services on named volumes (not ephemeral)? Will an update wipe data?",
      "Check security: exposed ports that should be internal, secrets in the file, running as root, latest tags.",
      "Check reliability: restart policies, healthchecks, dependency ordering, resource limits.",
      "Report each issue with severity and the exact fix; critique for the data-loss landmines first, revise once.",
    ],
    behaviorGuidelines: ["Data-loss risks are top priority", "Flag secrets in the file", "Concrete YAML fixes, not 'improve security'"],
    toolsAllowed: ["Read", "Grep"],
    toolsDisallowed: ["Write", "Edit", "Bash"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Review this docker-compose before I deploy", "Is this compose stack safe and reliable?"],
    successCriteria: ["Data-persistence risks caught", "Security issues flagged", "Each finding has a concrete fix"],
    failureModes: ["Missing an ephemeral-volume data-loss trap", "Ignoring exposed ports/secrets", "Vague advice"],
    followUpBehavior: "Offer to apply the fixes (with confirmation).",
  },
  {
    id: "log-analyzer",
    name: "Log Analyzer",
    category: "it",
    description: "Read through logs to find the real signal — errors, patterns, and root cause.",
    purpose: "Turn a wall of logs into what actually happened and what to do about it.",
    whenToUse: "Something went wrong and the answer is in the logs.",
    inputs: ["The log file/output (or where to find it) and the symptom/time window"],
    outputs: ["The key error(s), the sequence of events, the likely cause, and next steps"],
    steps: [
      "Establish the symptom and the time window to focus on, so you're not drowning in noise.",
      "Find the errors/warnings and the first occurrence — the first failure usually matters more than the cascade after it.",
      "Reconstruct the sequence of events around the failure; distinguish the trigger from downstream noise.",
      "State the likely root cause and the evidence; if unconfirmed, say so and give the next diagnostic step.",
      "Critique: did you anchor on the first failure rather than the loudest later error? Adjust if not.",
    ],
    behaviorGuidelines: ["Find the FIRST failure, not just the loudest", "Separate trigger from cascade", "Quote the actual log lines as evidence"],
    toolsAllowed: ["Bash", "Read", "Grep"],
    toolsDisallowed: ["Write", "Edit"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Analyze these logs and tell me why the service crashed", "What's causing these errors in the log?"],
    successCriteria: ["First failure identified", "Event sequence reconstructed", "Cause supported by quoted lines"],
    failureModes: ["Anchoring on the loudest downstream error", "No timeline", "Guessing the cause"],
    followUpBehavior: "Offer the next diagnostic step or a fix if the cause is clear.",
  },
  {
    id: "backup-plan",
    name: "Backup Plan Builder",
    category: "it",
    description: "Design a backup and recovery plan that would actually survive a disaster.",
    purpose: "Build a 3-2-1-style plan with tested recovery — not just 'we copy files sometimes'.",
    whenToUse: "Setting up or reviewing backups for important data/systems.",
    inputs: ["What needs protecting, how much loss is tolerable (RPO), and how fast you must recover (RTO)"],
    outputs: ["A backup plan: what · how often · where (incl. offsite) · retention · and a restore test"],
    steps: [
      "Identify what truly needs backing up and the tolerance: how much data loss is acceptable (RPO) and how fast you must be back (RTO).",
      "Design coverage: what to back up, frequency, at least one offsite/offline copy, and retention.",
      "Critically: define how recovery is TESTED — an untested backup is a hope, not a plan.",
      "Flag the current gaps versus this plan and the highest-priority one to fix.",
      "Critique for the single-copy and never-tested traps, then revise once.",
    ],
    behaviorGuidelines: ["Untested backups don't count — include a restore test", "Insist on an offsite/offline copy", "Tie frequency to the stated RPO"],
    toolsAllowed: ["Read", "Bash", "Write"],
    toolsDisallowed: ["Edit"],
    safetyLevel: "writes-files",
    confirmationRequired: false,
    examplePrompts: ["Design a backup plan for my homelab", "Review my backup strategy for gaps"],
    successCriteria: ["Coverage meets the stated RPO/RTO", "Includes offsite + a restore test", "Gaps prioritized"],
    failureModes: ["Single copy, same machine", "No restore test", "Frequency mismatched to RPO"],
    followUpBehavior: "Offer to script the backup or a restore-test procedure.",
  },
  {
    id: "security-hardening-review",
    name: "Security Hardening Review",
    category: "it",
    description: "Review a system/service for exposure and give specific hardening steps.",
    purpose: "Reduce attack surface with concrete, prioritized hardening — read-only.",
    whenToUse: "Before exposing a service, or auditing one that's already exposed.",
    inputs: ["The system/service config and how it's exposed"],
    outputs: ["Exposure findings by severity, each with a specific hardening step"],
    steps: [
      "Map the attack surface: what's exposed, to whom, and how it authenticates.",
      "Check for: default/weak creds, unnecessary exposed ports, missing auth/TLS, over-broad permissions, unpatched versions, secrets at rest.",
      "For each finding give severity, why it's exploitable, and the specific hardening step.",
      "Prioritize by exploitability × impact and call out the single most urgent fix.",
      "Critique for the 'works but wide open' issues, then revise once. Do not make changes — recommend them.",
    ],
    behaviorGuidelines: ["Read-only — recommend, don't change", "Concrete steps, not 'harden the server'", "Prioritize by real exploitability"],
    toolsAllowed: ["Bash", "Read", "Grep"],
    toolsDisallowed: ["Write", "Edit"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Review this service for security before I expose it", "Harden my self-hosted setup"],
    successCriteria: ["Real exposure found", "Each finding is actionable", "Prioritized by exploitability"],
    failureModes: ["Generic checklist with no specifics", "Making changes during an audit", "Missing the exposed admin/default creds"],
    followUpBehavior: "Offer to apply the top hardening step (with confirmation).",
  },
  {
    id: "incident-writeup",
    name: "Incident Writeup",
    category: "it",
    description: "Turn a resolved incident into a blameless postmortem with timeline and follow-ups.",
    purpose: "Document what happened and what prevents recurrence, from evidence.",
    whenToUse: "After an outage/bug/security event when you owe a clear writeup.",
    inputs: ["What happened and any logs/messages with timestamps"],
    outputs: ["Summary · Timeline · Root cause · Impact · Resolution · Follow-ups"],
    steps: [
      "Pin the facts and the four timestamps (started, detected, mitigated, resolved); read logs for exact times, never invent them.",
      "Build a chronological timeline: detection → diagnosis → mitigation → resolution, each with a time and action.",
      "State root cause separately from symptom; if unconfirmed, say so with the best-supported hypothesis.",
      "Quantify impact (who, how long, blast radius) and list owner-assignable preventive follow-ups.",
      "Critique that the root cause is supported and the tone is blameless, then revise once.",
    ],
    behaviorGuidelines: ["Blameless and factual", "Never invent a timestamp", "Root cause separate from symptom"],
    toolsAllowed: ["Read", "Bash", "Grep", "Write"],
    toolsDisallowed: ["Edit"],
    safetyLevel: "writes-files",
    confirmationRequired: false,
    examplePrompts: ["Write a postmortem for last night's outage", "Turn these logs into an incident report"],
    successCriteria: ["Evidence-based timeline", "Root cause vs symptom separated", "Owner-assignable follow-ups"],
    failureModes: ["Invented timestamps", "Blaming a person", "Symptom mistaken for cause"],
    followUpBehavior: "Surface the single highest-priority follow-up to prevent recurrence.",
  },
];
