import type { Skill } from "./types";

export const LEARNING_SKILLS: Skill[] = [
  {
    id: "tutor-mode",
    name: "Tutor Mode",
    category: "learning",
    description: "Teach a concept at the learner's level, checking understanding as you go.",
    purpose: "Help someone actually learn a topic, not just receive an explanation.",
    whenToUse: "You want to understand something, not just get an answer.",
    inputs: ["The topic", "Your current level and what you already know"],
    outputs: ["A guided explanation with checks for understanding and a clear next step"],
    steps: [
      "Establish what the learner already knows and the specific thing they want to understand. Ask one question only if their level is unclear.",
      "Explain from their level up: start concrete, build to the general, use one good analogy and a worked example.",
      "Check understanding with a quick question before moving on; adjust depth based on the gap.",
      "Summarize the key idea in one line and give the next thing to learn or practice.",
      "Critique whether the explanation matched their level (not too basic/advanced), then adjust.",
    ],
    behaviorGuidelines: ["Meet the learner where they are", "Concrete-first, then general", "Check understanding instead of monologuing"],
    toolsAllowed: ["WebSearch", "Read"],
    toolsDisallowed: ["Bash"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Teach me how JWT auth works, I'm a junior dev", "Help me understand compound interest"],
    successCriteria: ["Pitched at the learner's level", "Includes a worked example and a check", "Ends with a next step"],
    failureModes: ["Lecturing without checking", "Wrong level (too basic/advanced)", "Jargon with no grounding"],
    followUpBehavior: "Offer a practice question or the next concept.",
  },
  {
    id: "quiz-generator",
    name: "Quiz Generator",
    category: "learning",
    description: "Generate a quiz that tests real understanding of a topic.",
    purpose: "Create questions that check comprehension, not just recall, with an answer key.",
    whenToUse: "Studying, teaching, or assessing knowledge of a topic.",
    inputs: ["The topic or source material", "Difficulty and how many questions"],
    outputs: ["A quiz with a mix of question types + an answer key with explanations"],
    steps: [
      "Identify the key concepts that matter for this topic (from the source if given).",
      "Write questions that test understanding and application, not just definitions; mix recall, application, and one harder reasoning question.",
      "Provide an answer key with a one-line explanation for each, including why wrong options are wrong (for multiple choice).",
      "Critique: do the questions actually discriminate understanding, are any ambiguous or trick questions? Fix and revise once.",
    ],
    behaviorGuidelines: ["Test understanding, not just recall", "No ambiguous or trick questions", "Explain answers, not just mark them"],
    toolsAllowed: ["Read", "WebSearch"],
    toolsDisallowed: ["Bash"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Make a 10-question quiz on the French Revolution", "Quiz me on this chapter, medium difficulty"],
    successCriteria: ["Questions test understanding", "Answer key with explanations", "Appropriate difficulty"],
    failureModes: ["Pure definition recall", "Ambiguous questions", "Answers with no explanation"],
    followUpBehavior: "Offer to grade the user's answers or make a harder set.",
  },
  {
    id: "study-guide",
    name: "Study Guide Builder",
    category: "learning",
    description: "Condense material into a focused study guide built for retention.",
    purpose: "Turn a body of material into the high-yield notes that actually help you learn it.",
    whenToUse: "Preparing for an exam, interview, or to master a topic.",
    inputs: ["The material/topic and what you're studying for"],
    outputs: ["A structured guide: key concepts · must-knows · common confusions · self-test questions"],
    steps: [
      "Identify what's high-yield for the goal (the exam/interview/use), and prioritize accordingly — not everything is equally important.",
      "Organize concepts logically, with concise explanations and the relationships between them.",
      "Call out the things people commonly confuse or get wrong, and include a few self-test questions.",
      "Critique for coverage of the high-yield material and clarity, then revise once.",
    ],
    behaviorGuidelines: ["Prioritize high-yield over exhaustive", "Surface common confusions", "Build in active recall (self-test)"],
    toolsAllowed: ["Read", "WebSearch", "Write"],
    toolsDisallowed: ["Bash"],
    safetyLevel: "writes-files",
    confirmationRequired: false,
    examplePrompts: ["Make a study guide for this networking exam", "Build a study guide from these notes"],
    successCriteria: ["Focused on high-yield material", "Includes common confusions", "Has self-test prompts"],
    failureModes: ["Flat summary with no prioritization", "Missing common pitfalls", "No active-recall element"],
    followUpBehavior: "Offer flashcards or a quiz from the guide.",
  },
  {
    id: "explain-simply",
    name: "Explain Like I'm New",
    category: "learning",
    description: "Explain something complex in plain language without dumbing it down.",
    purpose: "Make a hard concept genuinely understandable to a smart non-expert.",
    whenToUse: "You need a clear, jargon-free explanation of something complicated.",
    inputs: ["The concept to explain", "Optionally, the analogy domain that would click for you"],
    outputs: ["A plain-language explanation with an analogy and the 'so what'"],
    steps: [
      "Identify the core of the concept — the one thing that, once understood, makes the rest click.",
      "Explain it in plain language with a concrete analogy; introduce necessary terms by defining them in passing.",
      "Add why it matters (the 'so what') and one example.",
      "Critique: did you keep accuracy while removing jargon, and would a smart newcomer get it? Revise once.",
    ],
    behaviorGuidelines: ["Plain language, but stay accurate", "One strong analogy beats five weak ones", "Define jargon inline, don't assume it"],
    toolsAllowed: ["WebSearch", "Read"],
    toolsDisallowed: ["Bash"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Explain how blockchains work, like I'm new", "What is a Kubernetes pod, in plain English?"],
    successCriteria: ["A newcomer understands it", "Accurate, not oversimplified to wrong", "Includes why it matters"],
    failureModes: ["Hidden jargon", "Dumbing it down into inaccuracy", "Analogy that misleads"],
    followUpBehavior: "Offer to go one level deeper now that the foundation is set.",
  },
];
