import type { Skill } from "./types";

export const PRODUCTIVITY_SKILLS: Skill[] = [
  {
    id: "weekly-planner",
    name: "Weekly Planner",
    category: "productivity",
    description: "Turn your goals and commitments into a realistic, prioritized week.",
    purpose: "Plan a week that protects time for what matters instead of just listing tasks.",
    whenToUse: "Start of the week, or when you feel scattered.",
    inputs: ["Your goals/commitments, deadlines, and roughly how much time you have"],
    outputs: ["A prioritized week with the top outcomes, time blocks, and what to drop"],
    steps: [
      "Gather the week's goals, fixed commitments, and deadlines. If capacity is unclear, ask one question.",
      "Identify the 1-3 outcomes that actually matter this week — the things you'd regret not doing.",
      "Allocate time realistically, accounting for meetings and buffer; protect focus blocks for the top outcomes.",
      "Explicitly name what to defer or drop — a plan that fits everything fits nothing.",
      "Critique for overcommitment, then revise once into a clean week view.",
    ],
    behaviorGuidelines: ["Be realistic about capacity, not aspirational", "Force prioritization — name what to drop", "Protect focus time for the top outcomes"],
    toolsAllowed: [],
    toolsDisallowed: ["Bash"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Plan my week — here are my goals and meetings", "Help me prioritize this week, I'm overloaded"],
    successCriteria: ["Top outcomes are clear and time-protected", "The plan fits realistic capacity", "What to drop is explicit"],
    failureModes: ["Overpacked plan", "Treating all tasks as equal", "Ignoring fixed commitments"],
    followUpBehavior: "Offer a daily breakdown or a time-blocked calendar version.",
  },
  {
    id: "project-plan",
    name: "Project Plan Builder",
    category: "productivity",
    description: "Break a project into phases, milestones, tasks, and dependencies.",
    purpose: "Turn a goal into an executable plan with a realistic sequence and clear milestones.",
    whenToUse: "Kicking off a project of any size.",
    inputs: ["The project goal, deadline, resources, and any known constraints"],
    outputs: ["Phases · milestones · tasks with dependencies · a critical path · risks"],
    steps: [
      "Clarify the goal, the hard deadline, and who/what is available. If the deadline or scope is unclear, ask one question.",
      "Break the work into phases and milestones, then tasks under each — sized small enough to estimate.",
      "Map dependencies and identify the critical path (the sequence that sets the timeline).",
      "Flag the top risks to the timeline and where buffer is needed.",
      "Critique for missing steps and unrealistic sequencing, then revise once.",
    ],
    behaviorGuidelines: ["Sequence by dependency, not wishful order", "Identify the critical path explicitly", "Tasks small enough to track"],
    toolsAllowed: ["Read"],
    toolsDisallowed: ["Bash"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Build a plan to launch this app in 6 weeks", "Plan the migration project end to end"],
    successCriteria: ["Realistic phases and milestones", "Dependencies and critical path identified", "Timeline risks flagged"],
    failureModes: ["Flat task list with no sequence", "Ignoring dependencies", "No critical path"],
    followUpBehavior: "Offer to turn it into a task board or a week-by-week schedule.",
  },
  {
    id: "task-breakdown",
    name: "Task Breakdown",
    category: "productivity",
    description: "Decompose a vague or daunting task into concrete, doable next actions.",
    purpose: "Unstick a big or fuzzy task by turning it into small, unambiguous steps.",
    whenToUse: "A task feels too big, vague, or hard to start.",
    inputs: ["The task and its goal"],
    outputs: ["An ordered list of small next actions, with the very first step called out"],
    steps: [
      "Clarify what 'done' looks like for the task.",
      "Break it into steps small enough that each is obviously doable in one sitting.",
      "Order them by dependency and call out the single first action to take right now.",
      "Flag any step that's actually a decision or a blocker needing input.",
      "Critique: is each step concrete enough to start without thinking? Revise once.",
    ],
    behaviorGuidelines: ["Each step is a concrete action, not a category", "Surface the very next physical action", "Separate decisions from doing"],
    toolsAllowed: [],
    toolsDisallowed: ["Bash"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Break down 'set up the new office' into steps", "I'm stuck on this task, help me start"],
    successCriteria: ["Steps are small and concrete", "First action is unambiguous", "Blockers/decisions are flagged"],
    failureModes: ["Steps that are still vague", "No clear starting point", "Mixing decisions into action steps"],
    followUpBehavior: "Offer to schedule the steps or tackle the first one now.",
  },
  {
    id: "prioritization",
    name: "Prioritization Assistant",
    category: "productivity",
    description: "Rank a messy list by impact and effort so you know what to do first.",
    purpose: "Cut through a long list to the few things that matter most right now.",
    whenToUse: "You have more to do than time and need to choose.",
    inputs: ["The list of tasks/options and what you're optimizing for (impact, urgency, etc.)"],
    outputs: ["A ranked list with do-now / schedule / delegate / drop buckets"],
    steps: [
      "Confirm what 'important' means here (revenue, deadline, unblocking others, etc.).",
      "Score each item on impact and effort/urgency; be explicit, not vibes-based.",
      "Sort into do-now, schedule, delegate, and drop — and be willing to put things in 'drop'.",
      "Call out the single highest-leverage item to do first.",
      "Critique for recency/anxiety bias (loud ≠ important), then revise once.",
    ],
    behaviorGuidelines: ["Optimize for the user's stated goal, not urgency theater", "Be willing to recommend dropping things", "Name the one highest-leverage item"],
    toolsAllowed: [],
    toolsDisallowed: ["Bash"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Prioritize this backlog for me", "What should I do first out of these 12 things?"],
    successCriteria: ["Ranked against the real goal", "Clear buckets including 'drop'", "One first action named"],
    failureModes: ["Ranking by loudness/urgency only", "Refusing to drop anything", "No clear #1"],
    followUpBehavior: "Offer to plan the do-now items into the day or week.",
  },
  {
    id: "meeting-actions",
    name: "Meeting → Actions",
    category: "productivity",
    description: "Turn raw notes or a transcript into decisions, owners, and dated action items.",
    purpose: "Convert a messy meeting into accountable outcomes nothing falls out of.",
    whenToUse: "You have notes/transcript and need clear follow-through.",
    inputs: ["The meeting notes or transcript"],
    outputs: ["Decisions · Action items (Owner — task — due date) · Open questions"],
    steps: [
      "Separate decisions, action items, and open questions; discard chit-chat.",
      "For each action item capture the task (verb + object), the named owner (mark 'unassigned' if none — don't guess), and the due date (or 'no date').",
      "Record each decision with any stated rationale so it survives the later 'why did we do this?'.",
      "List open questions with who must resolve each.",
      "Critique: is every action concrete, and did you invent anything not in the source? Remove inventions, revise once.",
    ],
    behaviorGuidelines: ["Only use what's in the source — never invent owners/decisions", "Concrete actions only", "Flag unassigned/undated items"],
    toolsAllowed: ["Read"],
    toolsDisallowed: ["Bash"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Turn these meeting notes into action items", "Extract decisions and owners from this transcript"],
    successCriteria: ["Decisions/actions/questions cleanly separated", "Each action has owner + date or is flagged", "Nothing invented"],
    failureModes: ["Inventing owners or dates", "Vague actions", "Losing a decision in the noise"],
    followUpBehavior: "Flag every action with no owner or date and offer to draft follow-up messages.",
  },
  {
    id: "ticket-drafter",
    name: "Ticket Drafter",
    category: "productivity",
    description: "Turn a vague request into a well-formed ticket with testable acceptance criteria.",
    purpose: "Produce a ticket an engineer can start from without asking follow-ups.",
    whenToUse: "Someone sends a fuzzy ask that needs to become trackable work.",
    inputs: ["The raw request"],
    outputs: ["A ticket: Title · Context · Acceptance criteria · Priority · Notes/assumptions"],
    steps: [
      "Extract the desired outcome (not the proposed solution), who wants it, and why now.",
      "Ask one clarifying question only if a missing detail blocks a useful ticket; otherwise note assumptions.",
      "Write an imperative, specific title; a context paragraph; and 2-5 acceptance criteria as verifiable outcomes.",
      "Add priority with a one-line justification, affected components, and inferred dependencies/risks.",
      "Critique: could a fresh engineer start from this alone, and are the criteria testable? Revise once.",
    ],
    behaviorGuidelines: ["Capture the outcome, not the requester's solution", "Acceptance criteria must be testable", "State assumptions explicitly"],
    toolsAllowed: ["Read"],
    toolsDisallowed: ["Bash"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Turn this Slack message into a proper ticket", "Make a ticket: users want to export their data"],
    successCriteria: ["Startable from the ticket alone", "Testable acceptance criteria", "Assumptions/unknowns noted"],
    failureModes: ["Copying the vague request", "Untestable criteria", "Encoding the requester's solution as the goal"],
    followUpBehavior: "Note what's still unknown and offer to split it if it's too big.",
  },
];
