import type { Skill } from "./types";

export const RESEARCH_SKILLS: Skill[] = [
  {
    id: "research-brief",
    name: "Research Brief",
    category: "research",
    description: "Research a question across sources and synthesize a cited, decision-ready brief.",
    purpose: "Produce a grounded answer to a real question, with sources and honest uncertainty.",
    whenToUse: "You need a trustworthy answer on something current or unfamiliar.",
    inputs: ["The question", "The decision or output it feeds"],
    outputs: ["Bottom line · Key findings (cited) · Disagreements/uncertainties · What's unverified"],
    steps: [
      "Restate the question and the decision it feeds, so the research stays targeted.",
      "Search 4+ independent sources, preferring primary/official ones; note each source's date and flag anything stale.",
      "Extract findings and state explicitly where sources agree vs disagree — don't average away real disagreement.",
      "Adversarially check load-bearing claims; if a claim rests on one weak source, say so.",
      "Synthesize: answer first, evidence, uncertainties, and what you couldn't verify. Critique for bias, revise once.",
    ],
    behaviorGuidelines: ["Don't answer from memory on time-sensitive facts", "Cite sources inline", "Surface disagreement instead of smoothing it"],
    toolsAllowed: ["WebSearch", "WebFetch", "Read"],
    toolsDisallowed: ["Bash", "Write", "Edit"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Research whether we should use Postgres or SQLite for this", "What's the current state of EU AI regulation?"],
    successCriteria: ["Answer is grounded in cited sources", "Agreement/disagreement is explicit", "Unverified claims are marked"],
    failureModes: ["Answering from memory", "Single-source confidence", "Hiding contradictions"],
    followUpBehavior: "Offer the recommended next step or the one question still worth resolving.",
  },
  {
    id: "compare-options",
    name: "Compare Options",
    category: "research",
    description: "Evaluate 2-5 options against the criteria that actually matter and recommend one.",
    purpose: "Turn a fuzzy 'which should I pick' into a structured comparison with a clear recommendation.",
    whenToUse: "Choosing between tools, vendors, approaches, or products.",
    inputs: ["The options", "What matters to you (cost, time, risk, fit, etc.) and any hard constraints"],
    outputs: ["A comparison table on the key criteria + a recommendation with rationale"],
    steps: [
      "Establish the decision criteria and their relative weight, plus any deal-breaker constraints. If the top criterion is unclear, ask one question.",
      "Gather the facts for each option (research if needed); note where information is missing rather than guessing.",
      "Build a comparison across the criteria — concrete values, not vibes.",
      "Recommend one option and explain why, including what would change the answer.",
      "Critique for bias toward a familiar option, then revise once.",
    ],
    behaviorGuidelines: ["Compare on the user's criteria, not generic ones", "Mark unknowns as unknown", "State what would flip the recommendation"],
    toolsAllowed: ["WebSearch", "WebFetch", "Read"],
    toolsDisallowed: ["Bash"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Compare Stripe vs Paddle for my SaaS", "Which of these 3 laptops for video editing?"],
    successCriteria: ["Compared on the criteria that matter", "Facts are concrete and sourced where researched", "Clear, justified recommendation"],
    failureModes: ["Generic criteria", "Hedging with no recommendation", "Hidden bias toward the well-known option"],
    followUpBehavior: "Offer to deepen the comparison on any single criterion.",
  },
  {
    id: "risk-analysis",
    name: "Risk Analysis",
    category: "research",
    description: "Surface what could go wrong, how likely, how bad, and how to mitigate.",
    purpose: "Make risks explicit and prioritized before committing to a plan or change.",
    whenToUse: "Before a launch, migration, big decision, or commitment.",
    inputs: ["The plan/decision and its context"],
    outputs: ["A ranked risk register: risk · likelihood · impact · mitigation · early warning sign"],
    steps: [
      "Understand the plan and what success depends on.",
      "Enumerate risks across categories: technical, operational, financial, people, external/dependencies, security.",
      "For each, estimate likelihood and impact, and give a concrete mitigation plus an early-warning signal.",
      "Rank by likelihood × impact and call out the top 3 to address first.",
      "Critique for blind spots (the risks you'd rather not think about), then revise once.",
    ],
    behaviorGuidelines: ["Be concrete — 'the vendor's API rate limit' not 'technical risk'", "Include the uncomfortable risks", "Every risk gets a mitigation"],
    toolsAllowed: ["WebSearch", "WebFetch", "Read"],
    toolsDisallowed: ["Bash"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["What could go wrong with this database migration?", "Risk analysis for launching this product in Q3"],
    successCriteria: ["Risks are specific and categorized", "Each has a mitigation and warning sign", "Ranked by likelihood × impact"],
    failureModes: ["Generic risks", "No mitigations", "Avoiding the real risks"],
    followUpBehavior: "Offer to turn the top risks into a mitigation checklist.",
  },
  {
    id: "competitor-analysis",
    name: "Competitor Analysis",
    category: "research",
    description: "Map competitors' positioning, strengths, gaps, and what it means for you.",
    purpose: "Understand the competitive landscape well enough to position against it.",
    whenToUse: "Entering a market, pricing a product, or sharpening positioning.",
    inputs: ["Your product/market", "Named competitors (or ask the agent to find them)"],
    outputs: ["Per-competitor: positioning · strengths · weaknesses · pricing signal · gap you can exploit"],
    steps: [
      "Identify the real competitors (research if not given) and confirm the segment you're comparing within.",
      "For each, capture positioning, target customer, key strengths, visible weaknesses, and pricing signal — from their own site/material where possible.",
      "Identify the gaps and underserved needs none of them address well.",
      "Synthesize what it means for your positioning and where to differentiate.",
      "Critique for stale or assumed info, mark anything unverified, then revise once.",
    ],
    behaviorGuidelines: ["Use the competitors' own current material where possible", "Separate fact from inference", "Find the gap, don't just describe the field"],
    toolsAllowed: ["WebSearch", "WebFetch", "Read"],
    toolsDisallowed: ["Bash"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Analyze competitors for a self-hosted notes app", "Who competes with us and where are the gaps?"],
    successCriteria: ["Competitors and segment correct", "Strengths/weaknesses grounded in real material", "A clear differentiation opportunity identified"],
    failureModes: ["Made-up details", "Listing competitors without a takeaway", "Missing the obvious leader"],
    followUpBehavior: "Offer to draft positioning that exploits the identified gap.",
  },
];
