import type { Skill } from "./types";

export const WRITING_SKILLS: Skill[] = [
  {
    id: "rewrite-for-clarity",
    name: "Rewrite for Clarity",
    category: "writing",
    description: "Tighten any text so it's clearer and shorter without losing meaning.",
    purpose: "Turn dense, rambling, or unclear writing into something crisp and readable.",
    whenToUse: "You have a draft that's hard to follow or too long.",
    inputs: ["The text to rewrite", "Optionally, the audience and any length target"],
    outputs: ["A clearer rewrite", "A one-line note on the main changes"],
    steps: [
      "Identify the core message and who it's for. If the audience is unclear and it changes the wording, ask one question.",
      "Rewrite: lead with the point, cut filler, prefer short sentences and concrete words, keep the original meaning and facts.",
      "Critique the rewrite against the success criteria — is it actually clearer and shorter, and did any meaning shift?",
      "Revise once, then present the result with a one-line summary of what changed.",
    ],
    behaviorGuidelines: ["Preserve the author's facts and intent exactly", "Cut, don't pad", "Don't add claims the original didn't make"],
    toolsAllowed: [],
    toolsDisallowed: ["Bash", "Write", "Edit"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Rewrite this paragraph to be clearer", "Make this half the length without losing the point"],
    successCriteria: ["Clearer and tighter than the original", "Meaning unchanged", "Reads naturally for the audience"],
    failureModes: ["Changing the meaning", "Adding fluff", "Making it shorter but more cryptic"],
    followUpBehavior: "Offer a more formal or more casual variant if useful.",
  },
  {
    id: "professional-email",
    name: "Professional Email Writer",
    category: "writing",
    description: "Draft a clear, appropriately-toned email that gets a response.",
    purpose: "Write an email that states its purpose, respects the reader's time, and has a clear ask.",
    whenToUse: "You need to send a professional email and want it to land well.",
    inputs: ["The goal of the email, who it's to, and any key facts/context"],
    outputs: ["A ready-to-send email with subject line", "Optionally, a softer/firmer variant"],
    steps: [
      "Identify the desired outcome, the recipient and your relationship, and the single clear ask. If the ask is missing, ask one question.",
      "Draft: a specific subject line, a one-line purpose up top, the necessary context, and an explicit ask with any deadline.",
      "Critique against the criteria — is the ask unmistakable, the tone right, and is it as short as it can be?",
      "Revise once and present the email; note the tone you chose.",
    ],
    behaviorGuidelines: ["One clear ask, surfaced early", "Match formality to the relationship", "Never invent facts/commitments the user didn't give"],
    toolsAllowed: [],
    toolsDisallowed: ["Bash"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Email a client to reschedule Friday's call to Monday", "Write a follow-up email asking for the signed contract"],
    successCriteria: ["The ask and any deadline are unmistakable", "Tone fits the recipient", "No unnecessary length"],
    failureModes: ["Burying the ask", "Wrong formality", "Inventing details"],
    followUpBehavior: "Offer a firmer or warmer variant, or a short follow-up version.",
  },
  {
    id: "executive-summary",
    name: "Executive Summary",
    category: "writing",
    description: "Compress a long document or topic into a decision-ready summary.",
    purpose: "Give a busy reader the bottom line, the why, and the decision in under a page.",
    whenToUse: "You have something long and need the leadership-ready version.",
    inputs: ["The source document/topic", "Who the summary is for and the decision it informs"],
    outputs: ["A one-paragraph bottom line + the key points + the recommendation/decision"],
    steps: [
      "Read or take in the full source. Identify the decision or question the reader actually cares about.",
      "Lead with the bottom line in 2-3 sentences — the answer, not a windup.",
      "Add the 3-5 supporting points that matter to that decision, and the recommendation or required decision.",
      "Critique: could an executive act on this without reading the source? Cut anything that isn't decision-relevant, then revise once.",
    ],
    behaviorGuidelines: ["Bottom line first, always", "Only include what changes the decision", "Stay faithful to the source — no new claims"],
    toolsAllowed: ["Read"],
    toolsDisallowed: ["Bash"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Summarize this 20-page report for the CEO", "Give me the executive summary of this proposal"],
    successCriteria: ["Reader can decide without the source", "Bottom line is first and clear", "Faithful to the original"],
    failureModes: ["Burying the conclusion", "Including detail that doesn't affect the decision", "Distorting the source"],
    followUpBehavior: "Offer to expand any point or produce a one-slide version.",
  },
  {
    id: "tone-adjuster",
    name: "Tone Adjuster",
    category: "writing",
    description: "Rewrite text in a specified tone while keeping the content intact.",
    purpose: "Shift the register of a piece (more formal, warmer, firmer, simpler) without changing what it says.",
    whenToUse: "The content is right but the tone is off for the audience.",
    inputs: ["The text", "The target tone (or the audience it needs to suit)"],
    outputs: ["The rewritten text in the target tone"],
    steps: [
      "Confirm the target tone and audience. If unstated and it matters, ask one question.",
      "Rewrite to hit that tone — adjust word choice, sentence length, and formality — while preserving every fact and the core message.",
      "Critique: does it consistently hold the target tone, and is the meaning unchanged?",
      "Revise once and present, noting the tone shift you made.",
    ],
    behaviorGuidelines: ["Change register, not substance", "Apply the tone consistently throughout", "Don't over-correct into a caricature"],
    toolsAllowed: [],
    toolsDisallowed: ["Bash"],
    safetyLevel: "read-only",
    confirmationRequired: false,
    examplePrompts: ["Make this message warmer and less corporate", "Rewrite this in a firmer, more direct tone"],
    successCriteria: ["Target tone is consistent", "Meaning preserved", "Reads naturally, not forced"],
    failureModes: ["Inconsistent tone", "Changing the content", "Overshooting into parody"],
    followUpBehavior: "Offer an alternative tone if the user is unsure.",
  },
  {
    id: "documentation-writer",
    name: "Documentation Writer",
    category: "writing",
    description: "Produce accurate docs grounded in the actual system, not aspiration.",
    purpose: "Write usage/setup/reference docs that reflect how something really works.",
    whenToUse: "A feature, API, or process is undocumented or the docs have drifted.",
    inputs: ["The thing to document (code, API, process) and where the docs should live"],
    outputs: ["Clear docs with runnable examples", "A note on any drift found between code and intent"],
    steps: [
      "Read the actual implementation/system first — docs must reflect reality, not intent.",
      "Write an overview, then setup/usage with examples that would actually run.",
      "Cover gotchas and edge cases concisely; if code and intended behavior disagree, flag it rather than paper over it.",
      "Critique for accuracy and completeness against the criteria, revise once, then write to the right file.",
    ],
    behaviorGuidelines: ["Verify against the source before writing", "Examples must be real and runnable", "Flag drift instead of hiding it"],
    toolsAllowed: ["Read", "Glob", "Grep", "Write", "Bash"],
    toolsDisallowed: [],
    safetyLevel: "writes-files",
    confirmationRequired: false,
    examplePrompts: ["Document this API module", "Write a setup guide for this project"],
    successCriteria: ["Docs match the actual behavior", "Examples run", "Concise and skimmable"],
    failureModes: ["Documenting intended-not-actual behavior", "Placeholder examples", "Wall of text"],
    followUpBehavior: "Offer to add a quickstart or a troubleshooting section.",
  },
];
